[project]
name = "ai_integration"
version = "0.1.0"
description = "Enterprise automation framework with multi-agent AI architecture"
requires-python = "==3.10.*"
dependencies = [
    "numpy==1.23.5",
    "networkx==2.8.4",
    "pandas==1.5.3",
    "scikit-learn==1.0.2",
    "tensorflow==2.9.3",
    "transformers==4.26.1",
    "pydantic==1.10.12",  # Using older version compatible with Python 3.10
    "rdflib==6.3.2"  # Using older version compatible with Python 3.10
]

[tool.setuptools]
packages = ["ai_integration", "ai_integration.agents"]