name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
      valkey:
        image: valkey/valkey:latest
        ports:
          - 6379:6379
      milvus:
        image: milvusdb/milvus:v2.3.4
        ports:
          - 19530:19530
          - 9091:9091
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linters
        run: |
          poetry run ruff .
          poetry run bandit -r src -ll
      - name: Run tests
        run: |
          poetry run pytest -q
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.18.0
        with:
          scan-type: filesystem
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
      - name: Scorecards
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
      - name: Upload Scorecards results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
